### ISSUE TITLE
是否考虑适配打开testflight链接或者打开分发平台地址?

### ISSUE THREAD

**Issue by j-gin** [azhon/FlutterAppUpdate#2]
您好:
    是否考虑适配打开testflight链接或者打开分发平台地址?

**Comment by azhon** [comment]
这个也是和打开AppStore一样是个链接吧

**Comment by j-gin** [comment]
> 这个也是和打开AppStore一样是个链接吧

不一样吧,我看AppStore是要id的, testflight与分发平台都是https的链接,
我测试 testflight链接直接跳转至Appstore了,打开页面是报错的,应该跳转到safari浏览器吧

**Comment by azhon** [comment]
那就是把链接开放一下就行了

**Comment by j-gin** [comment]
> 那就是把链接开放一下就行了

很给力啊,回复很及时.iOS代码我不会,要不然我自己搞,给你提个pr了.

**Comment by azhon** [comment]
我也不会iOS😌

**Comment by azhon** [comment]
已经改好了，可以使用一下；欢迎加群：828385813
