### ISSUE TITLE
versioncode 获取有问题

### ISSUE THREAD

**Issue by cyberdoors** [azhon/FlutterAppUpdate#4]
# 使用 flutter build apk --split-per-abi 进行编译 获取 versioncode 有问题

 使用 flutter buld apk  获取 versioncode 为 1
使用 flutter build apk --split-per-abi 获取的 versioncode 为 1001

**Comment by azhon** [comment]
这里获取的是build.gradle defaultConfig中声明的versionCode

**Comment by cyberdoors** [comment]
好的，谢谢
